server:
  port: 8899
spring:
  datasource:
    driver-class-name: org.h2.Driver # In production use postgres
    url: jdbc:h2:file:./toDos;DB_CLOSE_DELAY=1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true